name: Dev to Master Merge

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Git
        run: |
          git config --global user.name ""
          git config --global user.email ""

      - name: Merge development into main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff development -m "Automated merge of development into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
